#!/bin/bash
#
# NOTE:
# This file will be installed in /config/failover/tgrefresh and it will
# be called by /usr/lib/failover/f5tgrefresh
#
# - This file is for customer additions for tasks
#   to be performed when failover resolves an active/active conflict.
#
# - Refer to /usr/lib/failover/f5tgrefresh for more information
#



# Add delay when resolving active-active situations.
# This allows a script on the previously active now standby unit to
# finish running, before we start tryign to take the IPs back.
sleep 45

source /config/failover/f5-vip/venv/bin/activate
python /config/failover/f5-vip/f5-vip.py
